import React from "react";
// import ConfirmationMessage from "./ConfirmationMessage";

const ConfirmationMessage = (props) => {
  return (
    <div>
        props.message
      {/* <ConfirmationMessage
        message="Success!"
        backgroundColor="green"
      />
      <ConfirmationMessage
        message="Error occurred."
        backgroundColor="red"
      /> */}
    </div>
  );
};

export default ConfirmationMessage;
